<?php
namespace App\Support\BugInvestigator;
use App\Models\BugCase;
use App\Support\BugInvestigator\Collectors\{FailedJobCollector,InvoiceCollector,LogCollector,ProformaCollector,StockCollector,WarehouseIssueCollector};
use App\Support\BugInvestigator\Rules\{InvoiceRules,ProformaWorkflowRules,StockRules,WarehouseIssueRules};
class BugInvestigator { public function investigate(BugCase $case): array { $module=(new BugModuleClassifier())->classify($case->description,$case->module); $id=$case->entity_id; $state=['failed_jobs'=>(new FailedJobCollector())->collect(),'logs'=>(new LogCollector())->collect()]; $find=[];$broken=[];$files=[]; $add=function($pair)use(&$find,&$broken){[$f,$b]=$pair;$find=array_merge($find,$f);$broken=array_merge($broken,$b);}; if(in_array($module,['proforma','finance','warehouse','unknown'],true)){ $state['proformas']=(new ProformaCollector())->collect($case->entity_type==='proforma'?$id:null); $add((new ProformaWorkflowRules())->run($case->entity_type==='proforma'?$id:null)); $files[]='app/Http/Controllers/PreinvoiceController.php'; $files[]='app/Models/PreinvoiceOrder.php'; }
 if(in_array($module,['invoice','warehouse_issue','finance','unknown'],true)){ $state['invoices']=(new InvoiceCollector())->collect($case->entity_type==='invoice'?$id:null); $add((new InvoiceRules())->run($case->entity_type==='invoice'?$id:null)); $files[]='app/Http/Controllers/InvoiceController.php'; $files[]='app/Models/Invoice.php'; }
 if(in_array($module,['warehouse_issue','warehouse','unknown'],true)){ $state['warehouse_issues']=(new WarehouseIssueCollector())->collect($case->entity_type==='invoice'?$id:null); $add((new WarehouseIssueRules())->run($case->entity_type==='invoice'?$id:null)); $files[]='app/Http/Controllers/SalesHavalehController.php'; $files[]='app/Services/SalesHavalehService.php'; }
 if(in_array($module,['stock','purchase','warehouse','unknown'],true)){ $state['stock']=(new StockCollector())->collect($case->entity_type==='product'?$id:null); $add((new StockRules())->run($case->entity_type==='product'?$id:null)); $files[]='app/Services/InventoryService.php'; $files[]='app/Models/StockMovement.php'; }
 $summary=count($broken).' قانون شکسته و '.count($find).' شاهد/یادداشت پیدا شد.'; $result=['summary'=>$summary,'module'=>$module,'current_state'=>$state,'findings'=>array_values(array_unique($find)),'broken_rules'=>array_values(array_unique($broken)),'suspected_files'=>array_values(array_unique($files)),'probable_root_cause'=>count($broken)?'احتمالاً یکی از قوانین گردش کار یا همگام‌سازی رکوردهای مرتبط رعایت نشده است.':'شاهد قطعی از دیتابیس پیدا نشد؛ لاگ و مسیرهای کد بررسی شوند.','test_suggestion'=>'سناریوی توضیح داده‌شده را با رکوردهای مرتبط بسازید و انتظار گزارش/نمایش صحیح را assert کنید.']; $report=(new BugReportBuilder())->build($case,$result); $result['codex_prompt']=(new CodexPromptBuilder())->build($report); $result['raw_report']=$report; return $result; } }
