@extends('layouts.app')

@section('content')
@php
    $currentSort = $sort ?? 'id';
    $currentDir = $dir ?? 'desc';
    $toFa = fn ($value) => strtr((string) $value, ['0'=>'۰','1'=>'۱','2'=>'۲','3'=>'۳','4'=>'۴','5'=>'۵','6'=>'۶','7'=>'۷','8'=>'۸','9'=>'۹']);
    $money = fn ($value) => $toFa(\App\Support\Currency::formatRial($value ?? 0));
    $sortLink = function (string $key) use ($currentSort, $currentDir) {
        $nextDir = ($currentSort === $key && $currentDir === 'asc') ? 'desc' : 'asc';
        return route('products.index', array_merge(request()->query(), ['sort' => $key, 'dir' => $nextDir, 'page' => null]));
    };
    $sortArrow = fn (string $key) => $currentSort !== $key ? '↕' : ($currentDir === 'asc' ? '↑' : '↓');
    $user = auth()->user();
    $canDeleteProducts = $user && method_exists($user, 'hasAnyRole') && $user->hasAnyRole(['admin', 'Admin']);
@endphp

<style>
    :root{--brand:#0EA5B7;--brand-dark:#0F5965;--brand-deep:#12343D;--bg:#F4F6F8;--card:#fff;--soft:#F8FAFC;--border:#E2E8F0;--border-soft:#EEF2F7;--text:#1F2937;--muted:#6B7280;--radius:14px;--shadow:0 8px 24px rgba(15,23,42,.05)}
    body{background:var(--bg);color:var(--text);font-size:13.5px;overflow-x:hidden}.inventory-page{width:100%;max-width:1320px;margin:0 auto;padding:18px 16px 34px;overflow-x:hidden}.page-card{background:var(--card);border:1px solid var(--border);border-radius:var(--radius);box-shadow:var(--shadow)}
    .inventory-header{padding:18px 20px;margin-bottom:14px;border-right:5px solid var(--brand)}.inventory-header-inner{display:flex;justify-content:space-between;align-items:center;gap:14px;flex-wrap:wrap}.page-title{margin:0;font-size:1.2rem;font-weight:900;color:var(--brand-deep)}.page-subtitle{margin-top:7px;color:var(--muted);font-size:.82rem;line-height:1.8}.header-actions{display:flex;gap:8px;flex-wrap:wrap}.btn-soft,.btn-main{border-radius:10px;padding:8px 13px;font-size:.8rem;font-weight:800;display:inline-flex;align-items:center;justify-content:center;gap:6px;text-decoration:none;border:1px solid transparent;white-space:nowrap}.btn-main{background:var(--brand);color:#fff;border-color:var(--brand)}.btn-main:hover{background:var(--brand-dark);color:#fff}.btn-soft{background:#fff;color:var(--brand-deep);border-color:var(--border)}.btn-soft:hover{background:var(--soft);color:var(--brand-deep)}
    .toolbar-card{padding:15px;margin-bottom:14px}.toolbar-top{display:flex;justify-content:space-between;gap:12px;align-items:center;flex-wrap:wrap;margin-bottom:12px}.section-title{margin:0;font-size:.98rem;font-weight:900;color:var(--brand-deep)}.subtle-text{color:var(--muted);font-size:.78rem;line-height:1.8}.count-badge{background:#ECFEFF;color:var(--brand-dark);border:1px solid #BAE6FD;border-radius:999px;padding:6px 12px;font-size:.78rem;font-weight:850}.filter-toggle{display:none}.filter-grid{display:grid;grid-template-columns:minmax(260px,1.4fr) repeat(3,minmax(135px,.7fr)) auto;gap:9px;align-items:end}.label-sm{font-size:.74rem;font-weight:800;color:#526171;margin-bottom:6px}.form-control,.form-select{border-color:var(--border);border-radius:10px;color:var(--text);font-size:.82rem}.quick-search-mobile{display:none;margin-bottom:10px}
    .operation-strip{background:var(--soft);border:1px solid var(--border);border-radius:12px;padding:10px;display:grid;grid-template-columns:minmax(230px,1fr) auto;gap:10px;align-items:center;margin-bottom:13px}.selected-info{display:flex;align-items:center;gap:9px;min-width:0}.selected-dot{width:32px;height:32px;border-radius:10px;background:#DFF7FA;color:var(--brand-dark);display:inline-flex;align-items:center;justify-content:center;font-weight:900;flex:0 0 auto}.selected-title{font-weight:900;font-size:.84rem;color:var(--brand-deep);overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.selected-hint{color:var(--muted);font-size:.73rem;margin-top:2px}.operation-actions{display:flex;justify-content:flex-end;align-items:center;flex-wrap:wrap;gap:7px}.operation-actions .is-disabled,.operation-actions button:disabled{opacity:.45;pointer-events:none}.btn-mini{border-radius:10px;padding:7px 11px;font-size:.77rem;font-weight:800;display:inline-flex;align-items:center;justify-content:center;gap:5px;white-space:nowrap}.variant-operation-select{width:185px;height:35px;border-radius:10px;font-size:.77rem}.bulk-empty-message{display:none;color:var(--muted);font-size:.78rem;font-weight:800}
    .product-card-head{padding:14px 16px;border-bottom:1px solid var(--border);display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap}.table-wrap{width:100%;overflow-x:auto;padding:12px}.products-table{width:100%;min-width:0;table-layout:fixed;margin:0}.products-table th{background:#F8FAFC;color:#475569;font-size:.74rem;font-weight:900;padding:10px 8px;border-bottom:1px solid var(--border);white-space:nowrap}.products-table td{padding:10px 8px;font-size:.81rem;vertical-align:middle;border-bottom:1px solid var(--border-soft)}.products-table col.col-check{width:42px}.products-table col.col-toggle{width:44px}.products-table col.col-img{width:70px}.products-table col.col-name{width:auto}.products-table col.col-code{width:92px}.products-table col.col-sku{width:150px}.products-table col.col-stock{width:90px}.products-table col.col-status{width:105px}.products-table col.col-price{width:120px}.sortable-link{color:inherit;text-decoration:none;display:inline-flex;gap:6px}.sort-arrow{color:#94A3B8;font-size:.72rem}.mono{font-family:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono","Courier New",monospace;direction:ltr;unicode-bidi:plaintext}.truncate{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.product-thumb,.product-thumb-placeholder{width:50px;height:50px;border-radius:12px;border:1px solid var(--border);display:inline-flex;align-items:center;justify-content:center;background:var(--soft);overflow:hidden;color:var(--muted);font-size:1.1rem}.product-thumb img{width:100%;height:100%;object-fit:contain;background:#fff;padding:3px}.pill,.sellable-badge{display:inline-flex;align-items:center;justify-content:center;border-radius:999px;padding:4px 9px;font-size:.72rem;font-weight:800;border:1px solid var(--border);max-width:100%}.pill-gray{background:#F8FAFC;color:#475569}.pill-danger{background:#FEF2F2;border-color:#FECACA;color:#B91C1C}.pill-success{background:#F0FDF4;border-color:#BBF7D0;color:#15803D}.pill-purple{background:#ECFEFF;border-color:#BAE6FD;color:var(--brand-dark)}.sellable-badge.active{color:#166534;background:#ECFDF3;border-color:#BBF7D0}.sellable-badge.inactive{color:#475569;background:#F1F5F9;border-color:#CBD5E1}.price-inline{white-space:nowrap;font-weight:850;color:var(--brand-deep)}.empty-row{color:var(--muted);padding:36px 0!important;font-weight:800}.dropdown-menu{font-size:.8rem;text-align:right}.dropdown-item.text-danger{font-weight:800}
    .mobile-products{display:none}.mobile-card{background:#fff;border:1px solid var(--border);border-radius:14px;padding:11px;margin-bottom:10px;box-shadow:0 4px 14px rgba(15,23,42,.04);overflow:hidden}.mobile-card-top{display:grid;grid-template-columns:48px minmax(0,1fr) auto;gap:9px;align-items:center}.mobile-title{font-weight:900;color:var(--brand-deep);line-height:1.6;min-width:0}.mobile-meta,.mobile-values{display:flex;gap:8px;flex-wrap:wrap;margin-top:9px;color:var(--muted);font-size:.76rem}.mobile-values{justify-content:space-between;color:var(--text)}.mobile-actions{display:grid;grid-template-columns:1fr;gap:8px;margin-top:10px}.details-box{background:#F8FAFC;border:1px solid var(--border);border-radius:12px;padding:9px;margin-top:10px}.variant-list{display:grid;gap:7px}.variant-row{background:#fff;border:1px solid var(--border-soft);border-radius:10px;padding:8px;font-size:.76rem}.safe-break{overflow-wrap:anywhere;word-break:break-word}.pagination{margin-bottom:0}.products-pagination{padding:0 12px 12px}.offcanvas{border-top-left-radius:18px;border-bottom-left-radius:18px}.offcanvas-header{border-bottom:1px solid var(--border)}.cat-search{height:40px}.cat-tree-wrap{max-height:calc(100vh - 190px);overflow:auto}.side-link{font-size:.78rem;font-weight:800;color:var(--brand);text-decoration:none}.modal-content{border:0;border-radius:18px;box-shadow:0 22px 55px rgba(15,23,42,.18)}.modal-header{background:var(--brand-deep);color:#fff;border-bottom:0;border-radius:18px 18px 0 0}.modal-header .btn-close{filter:invert(1);opacity:.9}
    @media(max-width:1199.98px){.filter-grid{grid-template-columns:1fr 1fr}.filter-actions{grid-column:1/-1}.operation-strip{grid-template-columns:1fr}.operation-actions{justify-content:flex-start}}
    @media(max-width:767.98px){body{font-size:13px}.inventory-page{padding:10px 8px 24px}.inventory-header{padding:13px;margin-bottom:10px}.inventory-header-inner{display:block}.page-title{font-size:1.02rem}.page-subtitle{font-size:.76rem;margin-top:3px}.header-actions{display:grid;grid-template-columns:1fr;gap:7px;width:100%;margin-top:12px}.btn-soft,.btn-main{width:100%;min-height:39px}.toolbar-card{padding:10px;margin-bottom:10px}.toolbar-top{align-items:flex-start;margin-bottom:10px}.quick-search-mobile{display:block}.filter-toggle{display:inline-flex}.filter-panel{display:none;margin-top:10px}.filter-panel.is-open{display:block}.filter-grid{grid-template-columns:1fr;gap:8px}.filter-actions{display:grid!important;grid-template-columns:1fr 1fr;width:100%}.operation-strip{display:block;padding:9px}.selected-info{align-items:flex-start}.selected-title{white-space:normal;line-height:1.8}.operation-actions{display:none;grid-template-columns:1fr 1fr;gap:7px;margin-top:9px}.operation-strip.has-selection .operation-actions{display:grid}.operation-strip.has-selection .bulk-empty-message{display:none}.operation-strip:not(.has-selection) .bulk-empty-message{display:block;margin-top:8px}.operation-actions .variant-operation-select{grid-column:1/-1;width:100%;height:38px}.operation-actions .btn-mini{width:100%;min-height:38px}.desktop-products{display:none}.mobile-products{display:block;padding:9px}.product-card-head{padding:12px}.product-card-head .pill{display:none}.product-thumb,.product-thumb-placeholder{width:48px;height:48px;flex:0 0 48px}.mobile-card-top{grid-template-columns:48px minmax(0,1fr) auto}.mobile-actions .btn-mini{width:100%;min-height:36px}.offcanvas{width:min(88vw,360px)!important}}
    @media(max-width:390px){.operation-actions,.filter-actions,.mobile-actions{grid-template-columns:1fr}.operation-actions .variant-operation-select{grid-column:auto}.mobile-card-top{grid-template-columns:42px minmax(0,1fr) auto}.product-thumb,.product-thumb-placeholder{width:42px;height:42px}}
</style>

<div class="inventory-page">
    <div class="page-card inventory-header">
        <div class="inventory-header-inner">
            <div>
                <h1 class="page-title">مدیریت کالاها و موجودی</h1>
                <div class="page-subtitle">مدیریت کالا، موجودی، قیمت فروش، تنوع‌ها و کارتکس‌های انبار</div>
            </div>
            <div class="header-actions">
                <button class="btn-soft" type="button" data-bs-toggle="offcanvas" data-bs-target="#catOffcanvas">دسته‌بندی‌ها</button>
                @canPermission('stock_in.create')<a class="btn-soft" href="{{ route('purchases.create') }}">خرید کالا</a>@endcanPermission
                @canPermission('products.create')<a class="btn-main" href="{{ route('products.create') }}">افزودن کالا</a>@endcanPermission
            </div>
        </div>
    </div>

    <div id="productsAjaxArea">
        <div class="page-card toolbar-card">
            <div class="toolbar-top">
                <div>
                    <h2 class="section-title">عملیات و فیلتر کالاها</h2>
                    <div class="subtle-text">جستجوی سریع همیشه فعال است؛ فیلترهای بیشتر در موبایل جمع می‌شوند.</div>
                </div>
                <div class="d-flex gap-2 align-items-center flex-wrap">
                    <button class="btn-soft btn-mini filter-toggle" type="button" id="filterToggleBtn" aria-controls="productFilterPanel" aria-expanded="false">نمایش جستجو و فیلترها</button>
                    <div class="count-badge">{{ $toFa($products->total() ?? 0) }} کالا</div>
                </div>
            </div>

            <form method="GET" action="{{ route('products.index') }}" id="productFilterForm">
                @if(request('category_id'))<input type="hidden" name="category_id" value="{{ request('category_id') }}">@endif
                <input name="q" class="form-control quick-search-mobile" value="{{ request('q') }}" placeholder="جستجوی نام / کد / بارکد...">
                <div class="filter-panel" id="productFilterPanel">
                    <div class="filter-grid">
                        <div>
                            <label class="label-sm">جستجوی نام / کد / بارکد</label>
                            <input name="q" class="form-control d-none d-md-block" value="{{ request('q') }}" placeholder="نام / کد ۴ رقمی / بارکد محصول...">
                        </div>
                        <div><label class="label-sm">وضعیت موجودی</label><select name="stock_status" class="form-select"><option value="" @selected(request('stock_status') === '' || is_null(request('stock_status')))>همه</option><option value="out" @selected(request('stock_status') === 'out')>ناموجود</option></select></div>
                        <div><label class="label-sm">وضعیت فروش</label><select name="sellable_status" class="form-select"><option value="" @selected(request('sellable_status') === '' || is_null(request('sellable_status')))>همه</option><option value="sellable" @selected(request('sellable_status') === 'sellable')>قابل فروش</option><option value="unsellable" @selected(request('sellable_status') === 'unsellable')>غیرفعال</option></select></div>
                        <div><label class="label-sm">بازه قیمت فروش</label><div class="input-group"><input name="min_price" class="form-control money" value="{{ request('min_price') !== null ? \App\Support\Currency::toRial(request('min_price')) : '' }}" placeholder="از"><input name="max_price" class="form-control money" value="{{ request('max_price') !== null ? \App\Support\Currency::toRial(request('max_price')) : '' }}" placeholder="تا"></div></div>
                        <div class="filter-actions d-flex gap-2"><button class="btn btn-primary btn-mini px-3">اعمال</button><a class="btn btn-outline-secondary btn-mini px-3" href="{{ route('products.index') }}">پاک</a></div>
                    </div>
                </div>
            </form>

            <div class="operation-strip" id="operationStrip">
                <div class="selected-info"><div class="selected-dot" id="selectedCountBadge">۰</div><div class="min-w-0"><div class="selected-title" id="selectedProductTitle">هیچ کالایی انتخاب نشده است</div><div class="selected-hint" id="variantHelpText">برای عملیات گروهی، ابتدا کالا را انتخاب کنید.</div></div></div>
                <div class="bulk-empty-message">برای عملیات گروهی، ابتدا کالا را انتخاب کنید.</div>
                <div class="operation-actions">
                    @canPermission('products.edit')<button class="btn btn-primary btn-mini" type="button" id="bulkEditBtn">ویرایش</button>@endcanPermission
                    @canPermission('products.delete')<button class="btn btn-outline-danger btn-mini" type="button" id="bulkDeleteBtn">حذف</button>@endcanPermission
                    <button class="btn btn-outline-danger btn-mini" type="button" id="bulkDeactivateBtn">غیرفعال‌سازی</button>
                    <select id="bulkVariantSelect" class="form-select form-select-sm variant-operation-select" disabled><option value="">تنوع محصول...</option></select>
                    <button class="btn btn-outline-primary btn-mini" type="button" id="bulkStockBtn">موجودی انبار</button>
                    <button class="btn btn-outline-secondary btn-mini" type="button" id="bulkSalesLedgerBtn">کارتکس فروش</button>
                    <button class="btn btn-outline-secondary btn-mini" type="button" id="bulkPurchaseLedgerBtn">کارتکس خرید</button>
                </div>
            </div>
        </div>

        <div class="page-card product-card">
            <div class="product-card-head"><div><h2 class="section-title">لیست کالاها</h2><div class="subtle-text">نمایش {{ $toFa($products->firstItem() ?? 0) }} تا {{ $toFa($products->lastItem() ?? 0) }} از {{ $toFa($products->total() ?? 0) }} مورد</div></div><span class="pill pill-purple">لیست عملیاتی کالاها</span></div>

            <div class="desktop-products table-wrap">
                <table class="products-table">
                    <colgroup><col class="col-check"><col class="col-toggle"><col class="col-img"><col class="col-name"><col class="col-code"><col class="col-sku"><col class="col-stock"><col class="col-status"><col class="col-price"></colgroup>
                    <thead><tr><th class="text-center"><input type="checkbox" class="form-check-input select-all-products" title="انتخاب همه"></th><th>*</th><th>عکس</th><th><a href="{{ $sortLink('name') }}" class="sortable-link">نام کالا <span class="sort-arrow">{{ $sortArrow('name') }}</span></a></th><th><a href="{{ $sortLink('short_barcode') }}" class="sortable-link">کد کالا <span class="sort-arrow">{{ $sortArrow('short_barcode') }}</span></a></th><th><a href="{{ $sortLink('barcode') }}" class="sortable-link">بارکد / SKU <span class="sort-arrow">{{ $sortArrow('barcode') }}</span></a></th><th><a href="{{ $sortLink('stock') }}" class="sortable-link">موجودی مرکزی <span class="sort-arrow">{{ $sortArrow('stock') }}</span></a></th><th>وضعیت فروش</th><th><a href="{{ $sortLink('price') }}" class="sortable-link">قیمت فروش <span class="sort-arrow">{{ $sortArrow('price') }}</span></a></th></tr></thead>
                    <tbody>
                    @forelse($products as $p)
                        @include('products.partials.index-row-data', ['p' => $p, 'toFa' => $toFa, 'money' => $money, 'canDeleteProducts' => $canDeleteProducts, 'centralWarehouseId' => $centralWarehouseId, 'mode' => 'desktop'])
                    @empty
                        <tr><td colspan="9" class="text-center empty-row">هیچ کالایی ثبت نشده است.</td></tr>
                    @endforelse
                    </tbody>
                </table>
            </div>

            <div class="mobile-products">
                @forelse($products as $p)
                    @include('products.partials.index-row-data', ['p' => $p, 'toFa' => $toFa, 'money' => $money, 'canDeleteProducts' => $canDeleteProducts, 'centralWarehouseId' => $centralWarehouseId, 'mode' => 'mobile'])
                @empty
                    <div class="text-center empty-row">هیچ کالایی ثبت نشده است.</div>
                @endforelse
            </div>

            <div class="products-pagination mt-2">{{ $products->links() }}</div>
        </div>
    </div>
</div>

<div class="offcanvas offcanvas-end" tabindex="-1" id="catOffcanvas" aria-labelledby="catOffcanvasLabel"><div class="offcanvas-header"><h5 class="offcanvas-title fw-bold" id="catOffcanvasLabel">دسته‌بندی‌ها</h5><button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button></div><div class="offcanvas-body"><div class="d-flex justify-content-between align-items-center mb-2"><div class="fw-bold">انتخاب دسته‌بندی</div><a href="{{ route('products.index', request()->except(['category_id', 'page'])) }}" class="side-link">همه کالاها</a></div><input type="text" id="catSearchMobile" class="form-control cat-search mb-3" placeholder="جستجو در دسته‌ها..."><div class="cat-tree-wrap" id="catTreeMobile">@include('categories._tree', ['nodes' => $categoryTree])</div></div></div>
<form id="bulkDeleteForm" method="POST" class="d-none">@csrf @method('DELETE')</form>
<div class="modal fade" id="stockBreakdownModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-dialog-centered modal-lg"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="stockBreakdownTitle">موجودی کالا به تفکیک انبار</h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="بستن"></button></div><div class="modal-body"><div id="stockBreakdownProductName" class="fw-bold mb-3"></div><div class="table-responsive"><table class="table table-sm align-middle"><thead id="stockBreakdownHead"></thead><tbody id="stockBreakdownBody"></tbody></table></div></div></div></div></div>

<script>
document.addEventListener('DOMContentLoaded', function(){
    const deleteForm=document.getElementById('bulkDeleteForm');const modalEl=document.getElementById('stockBreakdownModal');const modal=modalEl?new bootstrap.Modal(modalEl):null;const stockTitleEl=document.getElementById('stockBreakdownTitle');const stockNameEl=document.getElementById('stockBreakdownProductName');const stockHeadEl=document.getElementById('stockBreakdownHead');const stockBodyEl=document.getElementById('stockBreakdownBody');
    const faNumber=v=>String(v??'').replace(/\d/g,d=>'۰۱۲۳۴۵۶۷۸۹'[d]);
    const parseJsonDataset=(raw,fallback=[])=>{if(!raw)return fallback;try{return JSON.parse(raw)}catch(e){return fallback}};
    const uniqueByProduct=items=>Array.from(new Map(items.map(ch=>[String(ch.dataset.productId||ch.value),ch])).values());
    function allChecks(){return Array.from(document.querySelectorAll('.product-checkbox'))}
    function selected(){return uniqueByProduct(allChecks().filter(ch=>ch.checked))}
    function syncProductChecks(productId,checked){allChecks().filter(ch=>String(ch.dataset.productId||ch.value)===String(productId)).forEach(ch=>{ch.checked=checked})}
    function single(){const s=selected();if(s.length!==1){alert('برای این عملیات باید دقیقا یک کالا انتخاب شود.');return null}return s[0]}
    function setActionState(count){['bulkEditBtn','bulkSalesLedgerBtn','bulkPurchaseLedgerBtn'].forEach(id=>{const el=document.getElementById(id);if(el)el.disabled=count!==1});const stock=document.getElementById('bulkStockBtn');if(stock)stock.disabled=count!==1;const del=document.getElementById('bulkDeleteBtn');if(del)del.disabled=count<1;const deact=document.getElementById('bulkDeactivateBtn');if(deact)deact.disabled=count<1}
    function productVariants(productId){const source=document.getElementById(`product-variants-${productId}`);return source?parseJsonDataset(source.textContent,[]):[]}
    function fillVariantSelect(item, preferredId=''){const variant=document.getElementById('bulkVariantSelect'),help=document.getElementById('variantHelpText');if(!variant)return;const productId=item.dataset.productId||item.value;const vars=productVariants(productId);variant.innerHTML='';if(!vars.length){variant.innerHTML='<option value="">این کالا تنوعی ندارد</option>';variant.disabled=true;if(help)help.textContent='این کالا تنوع ثبت‌شده‌ای ندارد؛ عملیات روی کل کالا انجام می‌شود.';return}variant.disabled=false;if(vars.length>1){variant.insertAdjacentHTML('beforeend','<option value="">همه تنوع‌ها / بدون انتخاب تنوع</option>')}vars.forEach(v=>{const o=document.createElement('option');o.value=String(v.id);const code=v.code||v.sku||v.barcode||'';o.textContent=`${v.name??'تنوع'}${code?` (${code})`:''} | موجودی مرکزی: ${faNumber(v.central_stock??0)}`;variant.appendChild(o)});variant.value=preferredId&&vars.some(v=>String(v.id)===String(preferredId))?String(preferredId):(vars.length===1?String(vars[0].id):'');if(help)help.textContent='برای کارتکس یا موجودی تفکیکی، تنوع موردنظر را انتخاب کنید.'}
    function updateBulkActionState(preferredVariantId=''){const s=selected(),strip=document.getElementById('operationStrip'),badge=document.getElementById('selectedCountBadge'),title=document.getElementById('selectedProductTitle'),help=document.getElementById('variantHelpText'),variant=document.getElementById('bulkVariantSelect'),deact=document.getElementById('bulkDeactivateBtn');strip?.classList.toggle('has-selection',s.length>0);setActionState(s.length);if(badge)badge.textContent=faNumber(s.length);if(!variant)return;if(!s.length){if(title)title.textContent='هیچ کالایی انتخاب نشده است';if(help)help.textContent='ابتدا یک کالا را انتخاب کنید';variant.innerHTML='<option value="">ابتدا یک کالا را انتخاب کنید</option>';variant.disabled=true;return}if(s.length>1){if(title)title.textContent=faNumber(s.length)+' کالا انتخاب شده است';if(help)help.textContent='انتخاب تنوع فقط برای یک کالا امکان‌پذیر است';variant.innerHTML='<option value="">انتخاب تنوع فقط برای یک کالا امکان‌پذیر است</option>';variant.disabled=true;return}const item=s[0];if(title)title.textContent=(item.dataset.productName||'کالای انتخاب شده')+' انتخاب شده است';if(deact)deact.textContent=item.dataset.isSellable==='1'?'غیرفعال‌سازی':'سوابق غیرفعال‌سازی';fillVariantSelect(item,preferredVariantId)}
    function bindProductSelection(){document.querySelectorAll('.select-all-products').forEach(sel=>{sel.onchange=function(){allChecks().forEach(ch=>syncProductChecks(ch.dataset.productId||ch.value,this.checked));updateBulkActionState()}});allChecks().forEach(ch=>{ch.onchange=function(e){syncProductChecks(this.dataset.productId||this.value,this.checked);updateBulkActionState()}})}
    function bindVariantToggles(){document.querySelectorAll('.variant-toggle').forEach(btn=>{btn.onclick=e=>e.stopPropagation();const target=document.querySelector(btn.getAttribute('data-bs-target'));const symbol=btn.querySelector('.variant-symbol');if(!target||!symbol)return;target.addEventListener('shown.bs.collapse',()=>symbol.textContent='−',{once:false});target.addEventListener('hidden.bs.collapse',()=>symbol.textContent='+',{once:false})})}
    function bindMobileVariantAccordions(){document.querySelectorAll('.mobile-variant-toggle').forEach(btn=>{btn.onclick=e=>e.stopPropagation()})}
    function bindVariantRowSelection(){document.querySelectorAll('.select-variant-btn,.variant-row-selectable').forEach(el=>{el.onclick=function(e){e.preventDefault();e.stopPropagation();const productId=this.dataset.productId,variantId=this.dataset.variantId;if(productId){syncProductChecks(productId,true);updateBulkActionState(variantId)}}})}
    function initProductsPageBindings(){bindProductSelection();bindVariantToggles();bindMobileVariantAccordions();bindVariantRowSelection();bindAjaxChrome();bindBulkActionButtons();updateBulkActionState()}
    function loadProducts(url,pushState=true){const area=document.getElementById('productsAjaxArea');if(!area)return;area.style.opacity='.55';fetch(url,{headers:{'X-Requested-With':'XMLHttpRequest'}}).then(r=>r.text()).then(html=>{const doc=new DOMParser().parseFromString(html,'text/html'),incoming=doc.getElementById('productsAjaxArea');if(!incoming){window.location.href=url;return}area.innerHTML=incoming.innerHTML;if(pushState)history.pushState({},'',url);initProductsPageBindings();const opened=bootstrap.Offcanvas.getInstance(document.getElementById('catOffcanvas'));opened?.hide()}).catch(()=>window.location.href=url).finally(()=>area.style.opacity='1')}
    function bindAjaxChrome(){document.getElementById('filterToggleBtn')?.addEventListener('click',function(){const panel=document.getElementById('productFilterPanel');panel?.classList.toggle('is-open');this.setAttribute('aria-expanded',panel?.classList.contains('is-open')?'true':'false');this.textContent=panel?.classList.contains('is-open')?'بستن جستجو و فیلترها':'نمایش جستجو و فیلترها'});document.getElementById('productFilterForm')?.addEventListener('submit',function(e){e.preventDefault();const fd=new FormData(this);const quick=this.querySelector('.quick-search-mobile');if(quick&&quick.value)fd.set('q',quick.value);loadProducts(`${this.action}?${new URLSearchParams(fd).toString()}`)});document.querySelectorAll('#productsAjaxArea a.sortable-link,#productsAjaxArea .pagination a,#catTreeMobile a').forEach(a=>a.addEventListener('click',function(e){if(!this.href||!this.href.includes('/products'))return;e.preventDefault();loadProducts(this.href)}));document.querySelector('#productsAjaxArea a.btn-outline-secondary[href*="products"]')?.addEventListener('click',function(e){e.preventDefault();loadProducts(this.href)})}
    function bindBulkActionButtons(){const edit=document.getElementById('bulkEditBtn');if(edit)edit.onclick=()=>{const s=single();if(s)location.href=s.dataset.editUrl};const del=document.getElementById('bulkDeleteBtn');if(del)del.onclick=()=>{const items=selected();if(!items.length)return;if(items.length>1){alert('حذف گروهی route جداگانه‌ای در این صفحه ندارد؛ لطفاً برای حذف، یک کالا انتخاب کنید.');return}const s=items[0];if(confirm(`کالای «${s.dataset.productName}» حذف شود؟`)){deleteForm.action=s.dataset.deleteUrl;deleteForm.submit()}};const deact=document.getElementById('bulkDeactivateBtn');if(deact)deact.onclick=()=>{const items=selected();if(!items.length)return;if(items.length>1){if(!confirm(faNumber(items.length)+' کالا برای غیرفعال‌سازی انتخاب شده است. به فرم سند غیرفعال‌سازی برویم؟'))return;const first=items[0];const url=new URL(first.dataset.deactivateUrl, window.location.origin);url.searchParams.delete('product_id');url.searchParams.set('product_ids', items.map(i=>i.value).join(','));location.href=url.toString();return}const s=items[0];location.href=s.dataset.isSellable==='1'?s.dataset.deactivateUrl:s.dataset.deactivationHistoryUrl};const stock=document.getElementById('bulkStockBtn');if(stock)stock.onclick=showStock;const purchase=document.getElementById('bulkPurchaseLedgerBtn');if(purchase)purchase.onclick=()=>goLedger('purchaseLedgerUrl');const sales=document.getElementById('bulkSalesLedgerBtn');if(sales)sales.onclick=()=>goLedger('salesLedgerUrl')}
    function goLedger(key){const s=single(),variant=document.getElementById('bulkVariantSelect');if(!s)return;const url=s.dataset[key];if(!url)return;const id=variant?.value||'';location.href=id?`${url}?variant_id=${encodeURIComponent(id)}`:url}
    async function showStock(){const s=selected(),variant=document.getElementById('bulkVariantSelect');if(!s.length||!modal)return;if(s.length>1){alert('نمایش موجودی تفکیکی فقط برای یک کالا امکان‌پذیر است.');return}const item=s[0],selectedVariantId=variant?.value||'',baseUrl=item.dataset.warehouseStockUrl;if(!baseUrl)return;const url=new URL(baseUrl,window.location.origin);if(selectedVariantId)url.searchParams.set('variant_id',selectedVariantId);stockTitleEl.textContent='موجودی کالا به تفکیک انبار';stockNameEl.textContent='در حال دریافت موجودی...';stockHeadEl.innerHTML='';stockBodyEl.innerHTML='<tr><td class="text-center text-muted">در حال دریافت اطلاعات...</td></tr>';modal.show();try{const response=await fetch(url.toString(),{headers:{'Accept':'application/json','X-Requested-With':'XMLHttpRequest'}});const payload=await response.json().catch(()=>({}));if(!response.ok){throw new Error(payload.message||Object.values(payload.errors||{})[0]?.[0]||'خطا در دریافت موجودی انبار.')}renderStockBreakdown(payload)}catch(error){stockNameEl.textContent='';stockHeadEl.innerHTML='';stockBodyEl.innerHTML=`<tr><td class="text-center text-danger">${error.message||'خطا در دریافت موجودی انبار.'}</td></tr>`}}
    function renderStockBreakdown(payload){const rows=Array.isArray(payload.rows)?payload.rows:[],variantMode=!!payload.is_variant_mode;stockTitleEl.textContent=`موجودی کالا به تفکیک انبار - ${payload.title||'کالای انتخاب‌شده'}`;stockNameEl.textContent=variantMode?'نمایش موجودی همین تنوع در انبارها':'نمایش موجودی همه تنوع‌های این کالا در انبارها';stockHeadEl.innerHTML=variantMode?'<tr><th>انبار</th><th class="text-end">موجودی کل</th><th class="text-end">رزرو در پیش‌فاکتور</th><th class="text-end">موجودی آزاد</th></tr>':'<tr><th>کالا / تنوع</th><th>انبار</th><th class="text-end">موجودی کل</th><th class="text-end">رزرو در پیش‌فاکتور</th><th class="text-end">موجودی آزاد</th></tr>';stockBodyEl.innerHTML='';if(!rows.length){const colspan=variantMode?4:5;stockBodyEl.innerHTML=`<tr><td colspan="${colspan}" class="text-center text-muted">برای کالای انتخاب‌شده در انبارها موجودی ثبت نشده است.</td></tr>`;return}rows.forEach(i=>{const tr=document.createElement('tr'),reserved=Number(i.reserved_quantity||0),warning=!!i.has_over_reserved_warning;const reservedText=reserved>0?`${faNumber(reserved)} عدد در پیش‌فاکتور`:'—';const warningText=warning?'<div class="small text-danger mt-1">رزرو ثبت‌شده از موجودی کل بیشتر است؛ لطفاً بررسی شود.</div>':'';const common=`<td>${i.warehouse_name??'—'}</td><td class="text-end fw-bold">${faNumber(i.total_quantity??0)}</td><td class="text-end ${reserved>0?'text-warning fw-bold':''}">${reservedText}</td><td class="text-end fw-bold ${warning?'text-danger':''}">${faNumber(i.available_quantity??0)}${warningText}</td>`;tr.innerHTML=variantMode?common:`<td>${i.variant_title??'—'}</td>${common}`;stockBodyEl.appendChild(tr)})}
    document.getElementById('catSearchMobile')?.addEventListener('input',function(){const q=this.value.trim().toLowerCase();document.querySelectorAll('#catTreeMobile a').forEach(a=>{const li=a.closest('li');if(li)li.style.display=!q||a.textContent.trim().toLowerCase().includes(q)?'':'none'})});initProductsPageBindings();window.addEventListener('popstate',()=>loadProducts(location.href,false));
});
</script>
@endsection
