@php
  $fmt = fn($n) => number_format((int) $n);
  $variantCode = fn($v) => $v?->variant_code ?: ($v?->sku ?: ($v?->barcode ?: ($v?->product?->code ?? '—')));
@endphp
@if($showFilters ?? false)
<div class="card wm-card mb-3"><div class="card-body"><form class="row g-2"><input type="hidden" name="tab" value="assign"><input type="hidden" name="warehouse_id" value="{{ $warehouseId }}"><div class="col-md-2"><select name="category_id" class="form-select"><option value="">دسته‌بندی</option>@foreach($categories as $c)<option value="{{ $c->id }}" @selected(request('category_id')==$c->id)>{{ $c->name }}</option>@endforeach</select></div><div class="col-md-3"><input name="q" class="form-control" value="{{ request('q') }}" placeholder="نام، کد، SKU یا بارکد"></div><div class="col-md-2"><select name="map_status" class="form-select"><option value="">همه</option><option value="mapped" @selected(request('map_status')==='mapped')>دارای مکان</option><option value="unmapped" @selected(request('map_status')==='unmapped')>بدون مکان</option><option value="multi" @selected(request('map_status')==='multi')>چندمکانه</option><option value="mismatch" @selected(request('map_status')==='mismatch')>دارای مغایرت</option></select></div><div class="col-md-1"><input name="zone" class="form-control" value="{{ request('zone') }}" placeholder="زون"></div><div class="col-md-1"><input name="rack" class="form-control" value="{{ request('rack') }}" placeholder="رک"></div><div class="col-md-1"><input name="box" class="form-control" value="{{ request('box') }}" placeholder="باکس"></div><div class="col-md-2"><button class="btn btn-dark w-100">اعمال فیلتر</button></div></form></div></div>
@endif
<div class="card wm-card"><div class="card-header bg-white fw-bold">{{ $title }}</div><div class="wm-table-wrap"><table class="table wm-table align-middle mb-0"><thead class="table-light"><tr><th>کالا</th><th>تنوع</th><th>کد / SKU / بارکد</th><th>موجودی کل</th><th>موجودی دارای مکان</th><th>موجودی بدون مکان</th><th>مکان‌های فعلی</th><th>عملیات</th></tr></thead><tbody>
@forelse($rows as $row)
  @php($variant=$row['variant'])
  <tr><td>{{ $variant->product?->name }}</td><td>{{ $variant->variant_name ?: $variant->variety_name ?: 'تنوع اصلی' }}</td><td dir="ltr">{{ $variantCode($variant) }}</td><td>{{ $fmt($row['total']) }}</td><td>{{ $fmt($row['mapped']) }}</td><td>@if($row['unmapped'] > 0)<span class="badge text-bg-warning">بدون مکان: {{ $fmt($row['unmapped']) }}</span>@elseif($row['mismatch'])<span class="badge text-bg-danger">مغایرت مکانی</span>@else<span class="badge text-bg-success">کامل</span>@endif @if($row['mismatch'])<div class="small text-danger mt-1">موجودی مکانی این تنوع بیشتر از موجودی کل ثبت‌شده است. لطفاً بررسی شود.</div>@endif</td><td>@forelse($row['locations'] as $stock)<div><span class="badge badge-soft" dir="ltr">{{ $stock->location?->code }}</span> — {{ $fmt($stock->quantity) }} عدد</div>@empty<span class="text-muted">بدون مکان</span>@endforelse</td><td><div class="action-stack">@if($canManage)<button class="btn btn-sm btn-success" onclick="document.querySelector('a[href=\'#locations-tab\']').click()">افزودن به مکان</button><button class="btn btn-sm btn-outline-dark" onclick="document.querySelector('a[href=\'#transfer-tab\']').click()">جابه‌جایی</button>@endif<button class="btn btn-sm btn-outline-primary" onclick="document.querySelector('a[href=\'#history-tab\']').click()">تاریخچه</button></div></td></tr>
@empty <tr><td colspan="8" class="text-center text-muted py-4">موردی یافت نشد.</td></tr>@endforelse
</tbody></table></div></div>
